<img src="https://drive.google.com/uc?id=1h6tCCKlZYAb2vZ265Ox8-zoSlSoutDBi" alt="drawing" width="150"/>

_Master en Data Analytics y Master Data Science._  
**Docente:** Luis Esteban Andaluz  
**Email:** luis_esteban_95@hotmail.es  
**Lindkedin:**  https://www.linkedin.com/in/luis-esteban-andaluz/


---



# 1- DATOS TABULARES

En este módulo veremos una base matemática imprescindible para desarrollar las distintas tareas de un Data Scientist.

## Índice:
* [Datos tabulares](#Tabulares)
* [Algebra con Numpy](#Numpy)
* [DataFrames con Pandas](#Pandas)
* [Ejercicios](#Ejercicios)

## Datos tabulares<a class="anchor" id="Tabulares"></a>

Todos los datos que se encuentran en las bases de datos SQL tradicionales tienen formato de tabla. Las tablas tienen filas y columnas que se pueden identificar por sus índices correspondientes. Índice de fila y nombre de las columnas


<img src="https://drive.google.com/uc?id=1jm3aLMnSHWbxeRxhkeMyg5hfyICTn4XK" alt="drawing" width="750"/>



Las bases de datos modernas, las páginas web y las aplicaciones que las sustentas pueden tener también bases de datos no basadas en tablas sino en formatos complejos como el JSON o documentos que combinan diferentes parejas de clave valor.


<img src="https://drive.google.com/uc?id=1aUCYJTIAv7_lMt7QWLfESL3XQ0vf9Mde" alt="drawing" width="750"/>


Sobre los datos tabulares resulta directo aplicar estadística. Sin embargo, si tenemos datos no estructurados seguramente necesitamos un procesado previo que nos ofrezca el dato de forma tabular.

## Algebra con Numpy<a class="anchor" id="Numpy"></a>


<img src="https://drive.google.com/uc?id=1A0PbVeeBHqN_Iee1IkRnCyTYY7loOa3V" alt="drawing" width="150"/>


Vamos a ver cómo importar nuestro primer módulo: [numpy](https://numpy.org/doc/stable/reference/index.html). Numpy es el módulo numérico de python y nos permite aplicar operaciones matemáticas sobre colecciones de datos llamadas arrays. Los arrays pueden tener una dimensión (vectores), dos dimensiones (matrices), o más, tensores.

Para el análisis de datos y el data science vectores y matrices son imprescindibles. Los tensores son comunes a la hora de utilizar técnicas de deep learning.

Aquí tienes una [cheatsheet de numpy.](http://datacamp-community-prod.s3.amazonaws.com/ba1fe95a-8b70-4d2f-95b0-bc954e9071b0)

Aquí tienes la [documentación de pandas.](https://numpy.org/doc/stable/reference/)

In [ ]:
import numpy as np

#### Arrays

In [ ]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
print("Una dimension")
print(a1D)
print("="*10)
print("Dos dimensiones")
print(a2D)
print("="*10)
print("Tres dimensiones")
print(a3D)
print("="*10)

Una dimension
[1 2 3 4]
Dos dimensiones
[[1 2]
 [3 4]]
Tres dimensiones
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Podemos definir el tipo de dato

In [ ]:
a = np.array([127, 128, 129], dtype=np.int8)

<ipython-input-5-601b7aa5074a>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([127, 128, 129], dtype=np.int8)
<ipython-input-5-601b7aa5074a>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([127, 128, 129], dtype=np.int8)


In [ ]:
print(a)

[ 127 -128 -127]


Podemos hacer operaciones con los arrays

In [ ]:
a = np.array([2, 3, 4], dtype=np.int8)
b = np.array([5, 6, 7], dtype=np.int8)
c = a - b
d = a * b
e = np.dot(a,b)

In [ ]:
print(c)
print(b)
print(e)

print(d)

print(np.sqrt(a))

[-3 -3 -3]
[5 6 7]
56
[10 18 28]
[1.414 1.732 2.   ]


Tenemos operaciones para tener secuencias de números

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Con la misma operación podemos especificar el tipo de dato y también establecer los límites.

In [ ]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

También podemos generar espacios de lin, arrays de números reales. Nosotros especificamos los límites del array y el número de elementos y estos toman valores que se distribuyen homogéneamente.

In [ ]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

#### Matrices

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.diag([1, 2, 3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [ ]:
print(a)

[[1 2]
 [3 4]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### DataFrames con Pandas <a class="anchor" id="Pandas"></a>


<img src="https://drive.google.com/uc?id=1g665UrA1o4sWzGzln8xyfDESZ7InosDS" alt="drawing" width="150"/>

Pandas es un módulo que nació en el seno de AQR Capital, una empresa de gestión de activos. Se publicó como proyecto open source en 2008 y hoy en día es el módulo más común para el trabajo con datos tabulares en python. Se beneficia de las operaciones matemáticas que se pueden hacer con numpy así como de modulos de visualización.

Aquí tienes una [cheatsheet de pandas.](http://datacamp-community-prod.s3.amazonaws.com/f04456d7-8e61-482f-9cc9-da6f7f25fc9b).

Aquí tienes la [documentación de pandas.](https://pandas.pydata.org/docs/reference/general_functions.html)

In [111]:
import pandas as pd

In [112]:
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                   columns=['a', 'b', 'c'])

In [113]:
df2.head()

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Antes de seguir... Pandas facilita mucho la lectura y escritura de ficheros. Vamos a cargar un dataset clásico, el de los [supervivientes del titanic.](https://www.kaggle.com/c/titanic)

In [114]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [115]:
df_titanic = pd.read_csv("1_modulo_matematico/titanic_train.csv")

FileNotFoundError: [Errno 2] No such file or directory: '1_modulo_matematico/titanic_train.csv'

In [ ]:
# con head vemos las primeras filas del dataframe
df_titanic.head()

NameError: name 'df_titanic' is not defined

In [ ]:
# podemos ver cuantas filas y columnas tiene el dataframe
df_titanic.shape

NameError: name 'df_titanic' is not defined

### Selección de campos y registros

In [ ]:
# utilizando el operador loc nos referimos a las filas y a las columnas por su NOMBRE:
df_titanic.loc[0, "Name"]

'Braund, Mr. Owen Harris'

In [ ]:
df_titanic.loc[5, :]

PassengerId                   6
Survived                      0
Pclass                        3
Name           Moran, Mr. James
Sex                        male
Age                         NaN
SibSp                         0
Parch                         0
Ticket                   330877
Fare                     8.4583
Cabin                       NaN
Embarked                      Q
Name: 5, dtype: object

In [ ]:
df_titanic.loc[:, "Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [ ]:
# La operacion loc resulta muy util para filtrar los registros:
df_titanic.loc[df_titanic["Age"] < 18]

PassengerId  Survived  Pclass                                     Name  \
7              8         0       3           Palsson, Master. Gosta Leonard   
9             10         1       2      Nasser, Mrs. Nicholas (Adele Achem)   
10            11         1       3          Sandstrom, Miss. Marguerite Rut   
14            15         0       3     Vestrom, Miss. Hulda Amanda Adolfina   
16            17         0       3                     Rice, Master. Eugene   
..           ...       ...     ...                                      ...   
850          851         0       3  Andersson, Master. Sigvard Harald Elias   
852          853         0       3                  Boulos, Miss. Nourelain   
853          854         1       1                Lines, Miss. Mary Conover   
869          870         1       3          Johnson, Master. Harold Theodor   
875          876         1       3         Najib, Miss. Adele Kiamie "Jane"   

        Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked  
7      male   2.0      3      1    349909  21.0750   NaN        S  
9    female  14.0      1      0    237736  30.0708   NaN        C  
10   female   4.0      1      1   PP 9549  16.7000    G6        S  
14   female  14.0      0      0    350406   7.8542   NaN        S  
16     male   2.0      4      1    382652  29.1250   NaN        Q  
..      ...   ...    ...    ...       ...      ...   ...      ...  
850    male   4.0      4      2    347082  31.2750   NaN        S  
852  female   9.0      1      1      2678  15.2458   NaN        C  
853  female  16.0      0      1  PC 17592  39.4000   D28        S  
869    male   4.0      1      1    347742  11.1333   NaN        S  
875  female  15.0      0      0      2667   7.2250   NaN        C  

[113 rows x 12 columns]

In [ ]:
# Despues podemos ver el numero de registros
len(df_titanic.loc[df_titanic["Age"] < 18])

113

In [ ]:
# Podemos combinar las condiciones
len(df_titanic.loc[(df_titanic["Age"] < 18) & (df_titanic["Sex"] == "female")])

55

In [ ]:
# Seria equivalente excluyendo el .loc
df_titanic[(df_titanic["Age"] < 18) & (df_titanic["Sex"] == "female")].head()

PassengerId  Survived  Pclass                                  Name  \
9            10         1       2   Nasser, Mrs. Nicholas (Adele Achem)   
10           11         1       3       Sandstrom, Miss. Marguerite Rut   
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina   
22           23         1       3           McGowan, Miss. Anna "Annie"   
24           25         0       3         Palsson, Miss. Torborg Danira   

       Sex   Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
9   female  14.0      1      0   237736  30.0708   NaN        C  
10  female   4.0      1      1  PP 9549  16.7000    G6        S  
14  female  14.0      0      0   350406   7.8542   NaN        S  
22  female  15.0      0      0   330923   8.0292   NaN        Q  
24  female   8.0      3      1   349909  21.0750   NaN        S

In [ ]:
# Se pueden concatenar filtros
df_titanic[(df_titanic["Age"] < 18)][(df_titanic[(df_titanic["Age"] < 18)]["Sex"] == "female")].head()

PassengerId  Survived  Pclass                                  Name  \
9            10         1       2   Nasser, Mrs. Nicholas (Adele Achem)   
10           11         1       3       Sandstrom, Miss. Marguerite Rut   
14           15         0       3  Vestrom, Miss. Hulda Amanda Adolfina   
22           23         1       3           McGowan, Miss. Anna "Annie"   
24           25         0       3         Palsson, Miss. Torborg Danira   

       Sex   Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
9   female  14.0      1      0   237736  30.0708   NaN        C  
10  female   4.0      1      1  PP 9549  16.7000    G6        S  
14  female  14.0      0      0   350406   7.8542   NaN        S  
22  female  15.0      0      0   330923   8.0292   NaN        Q  
24  female   8.0      3      1   349909  21.0750   NaN        S

In [ ]:
# Podemos crear una columna utilizando estas funciones
df_titanic["mayor_edad"] = 0
df_titanic.loc[df_titanic["Age"] >= 18, "mayor_edad"] = 1
df_titanic.head(15)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
5                                    Moran, Mr. James    male   NaN      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
7                      Palsson, Master. Gosta Leonard    male   2.0      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
12                     Saundercock, Mr. William Henry    male  20.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   

    Parch            Ticket     Fare Cabin Embarked  mayor_edad  
0       0         A/5 21171   7.2500   NaN        S           1  
1       0          PC 17599  71.2833   C85        C           1  
2       0  STON/O2. 3101282   7.9250   NaN        S           1  
3       0            113803  53.1000  C123        S           1  
4       0            373450   8.0500   NaN        S           1  
5       0            330877   8.4583   NaN        Q           0  
6       0             17463  51.8625   E46        S           1  
7       1            349909  21.0750   NaN        S           0  
8       2            347742  11.1333   NaN        S           1  
9       0            237736  30.0708   NaN        C           0  
10      1           PP 9549  16.7000    G6        S           0  
11      0            113783  26.5500  C103        S           1  
12      0         A/5. 2151   8.0500   NaN        S           1  
13      5            347082  31.2750   NaN        S           1  
14      0            350406   7.8542   NaN        S           0

In [ ]:
# Podemos eliminar columnas
del df_titanic["mayor_edad"]
df_titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
# Utilizando el operador .iloc nos referimos
df_titanic.iloc[:, 5]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

### Estructura de la tabla

In [ ]:
# Podemos ver las columas del data frame:
print(df_titanic.columns)
print(df_titanic.columns.tolist())

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


### Contar rápidamente valores

In [ ]:
# Podemos ver los valores que tienen las distintas columnas
df_titanic["Sex"].value_counts()

male      577
female    314
Name: Sex, dtype: int64

### Output de ficheros

In [ ]:
# Podemos guardar el dataframe también en un .csv o .xlsx con la siguiente instruccion
df_titanic.to_csv( "/content/drive/MyDrive/PONTIA - ESTADÍSTICA/1_modulo_matematico/ext1_titanic.csv", sep =";")
df_titanic.to_excel("/content/drive/MyDrive/PONTIA - ESTADÍSTICA/1_modulo_matematico/ext1_titanic.xlsx")

¿Te da un error? Debes instalar el módulo openpyxl con la instrucción:   

!pip install

### Agrupaciones
Una agrupación consiste en reducir la dimensión del dataframe quedándonos solo con los valores disponibles en ciertas columnas y generando columnas a partir de otras existentes y aplicando operaciones de agregación como contar, sumar, calcular el máximo, etc...

In [ ]:
df_titanic.groupby(["Sex", "Survived"]).agg({"Name": "count"})

Name
Sex    Survived      
female 0           81
       1          233
male   0          468
       1          109

## Ejercicios.  <a class="anchor" id="Ejercicios"></a>

### Ejercicio 1.
__¿Cuántos pasajeros sobrevivieron y cuántos no?__

### Ejercicio 2.
__Genera una nueva columna en el dataframe que se llame "billete_barato" y que tenga valor 1 si la columna "Fare" es menor de 10 y 0 si es mayor de 10__

### Ejercicio 3.
__Agrega el dataframe con la nueva columan por la columna "billete_barato" y por "Survived" y cuenta el número de clientes que caen en cada combinación. ¿Ves algún patrón?__